// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TorneoEntidades;

#nullable disable

namespace TorneoInfraestructura.Migrations
{
    [DbContext(typeof(TorneoContext))]
    [Migration("20241015021730_PrimerMigracion")]
    partial class PrimerMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TorneoEntidades.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoJugador")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int?>("TorneoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TorneoId");

                    b.ToTable("Jugadores");

                    b.HasDiscriminator<string>("TipoJugador").HasValue("Jugador");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TorneoEntidades.Torneo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("GanadorId")
                        .HasColumnType("int");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Torneos");
                });

            modelBuilder.Entity("TorneoEntidades.JugadorFemenino", b =>
                {
                    b.HasBaseType("TorneoEntidades.Jugador");

                    b.Property<decimal>("TiempoReaccion")
                        .HasColumnType("decimal(5, 2)");

                    b.HasDiscriminator().HasValue("Femenino");
                });

            modelBuilder.Entity("TorneoEntidades.JugadorMasculino", b =>
                {
                    b.HasBaseType("TorneoEntidades.Jugador");

                    b.Property<decimal>("Fuerza")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("Velocidad")
                        .HasColumnType("decimal(5, 2)");

                    b.HasDiscriminator().HasValue("Masculino");
                });

            modelBuilder.Entity("TorneoEntidades.Jugador", b =>
                {
                    b.HasOne("TorneoEntidades.Torneo", null)
                        .WithMany("Jugadores")
                        .HasForeignKey("TorneoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TorneoEntidades.Torneo", b =>
                {
                    b.Navigation("Jugadores");
                });
#pragma warning restore 612, 618
        }
    }
}
